const CM_TO_PX = 37.7952755906
const DEFAULT_PAGE_GAP = 50
const DEFAULT_HEADER_HEIGHT = 50
const DEFAULT_FOOTER_HEIGHT = 50
const DEFAULT_PAGE_BREAK_BACKGROUND = 'var(--umo-container-background)'

export {
  CM_TO_PX,
  DEFAULT_FOOTER_HEIGHT,
  DEFAULT_HEADER_HEIGHT,
  DEFAULT_PAGE_BREAK_BACKGROUND,
  DEFAULT_PAGE_GAP,
}
